Manager Wydatków/Controllers/StronaGController.cs
using Manager_Wydatkow.Models;
using Manager_Wydatkow.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace Manager_Wydatkow.Controllers
{
    public class StronaGController : Controller
    {
        private readonly AplikacjaDbContext _context;
        public StronaGController(AplikacjaDbContext context) 
        {
            _context= context;
        }

        // Get Action
        public IActionResult Login()
        {
            if (HttpContext.Session.GetString("Username") == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        //Post Action
        [HttpPost]
        public ActionResult Login(User u)
        {
            if (HttpContext.Session.GetString("Username") == null)
            {
                if (ModelState.IsValid)
                {
                    using (LoginDbContext db = new())
                    {
                        var obj = db.Users.Where(a => a.Username.Equals(u.Username) && a.Password.Equals(u.Password)).FirstOrDefault();
                        if (obj != null)
                        {
                            HttpContext.Session.SetString("Username", obj.Username.ToString());
                            return RedirectToAction("Index");
                        }
                    }
                }
            }
            else
            {
                
                return RedirectToAction("Login");
            }
            ViewData["LoginFlag"] = "Zła nazwa użytkownika lub hasło!";
            return View();
        }

        public ActionResult Logout()
        {
            HttpContext.Session.Clear();
            HttpContext.Session.Remove("Username");
            return RedirectToAction("Login");
        }

        [Authentication]
        public async Task<ActionResult> Index()
        {
            //ostatnie 7 dni
            DateTime StartDate = DateTime.Today.AddDays(-6);
            DateTime EndDate = DateTime.Today;

            List<Transakcje> SelectedTransakcjes = await _context.Transakcjes
                .Include(x => x.Kategoria)
                .Where(y => y.Data >=StartDate && y.Data <= EndDate)
                .ToListAsync();

            //Suma Wpływów
            int sumaW = SelectedTransakcjes
                .Where(i => i.Kategoria.Typ == "Wpływ")
                .Sum(j => j.Cena);
            ViewBag.SumaW = sumaW.ToString("c", CultureInfo.GetCultureInfo("pl-PL"));

            //Suma Wydatków
            int sumaWw = SelectedTransakcjes
                .Where(i => i.Kategoria.Typ == "Wydatek")
                .Sum(j => j.Cena);
            ViewBag.SumaWw = sumaWw.ToString("c", CultureInfo.GetCultureInfo("pl-PL"));

            //Stan konta
            int stanK = sumaW - sumaWw;
            ViewBag.StanK = stanK.ToString("c", CultureInfo.GetCultureInfo("pl-PL"));

            //Wykres - kategorie wydatków
            ViewBag.DoughnutChartData = SelectedTransakcjes
                .Where(i => i.Kategoria.Typ == "Wydatek")
                .GroupBy(j => j.Kategoria.KategoriaId)
                .Select(k => new
                {
                    kategoriaTytulIkona = k.First().Kategoria.Ikona+" "+ k.First().Kategoria.Tytul,
                    cena = k.Sum(j => j.Cena),
                    cenaFormat = k.Sum(j => j.Cena).ToString("c", CultureInfo.GetCultureInfo("pl-PL"))
                })
                .OrderByDescending(l=>l.cena)
                .ToList();

            //spline chart
            //wplywy

            List<SplineChartData> WplywyPodsumowanie = SelectedTransakcjes
                .Where(i => i.Kategoria.Typ == "Wpływ")
                .GroupBy(j => j.Data)
                .Select(k => new SplineChartData()
                {
                    dzien = k.First().Data.ToString("dd-MMM"),
                    wplywy = k.Sum(l => l.Cena)
                })
                .ToList();

            //wydatki

            List<SplineChartData> WydatkiPodsumowanie = SelectedTransakcjes
                .Where(i => i.Kategoria.Typ == "Wydatek")
                .GroupBy(j => j.Data)
                .Select(k => new SplineChartData()
                {
                    dzien = k.First().Data.ToString("dd-MMM"),
                    wydatki = k.Sum(l => l.Cena)
                })
                .ToList();
           
            // wydatki i wplywy
            //
            string[] Ostatnie7Dni = Enumerable.Range(0,7)
                .Select(i => StartDate.AddDays(i).ToString("dd-MMM"))
                .ToArray();

            ViewBag.SplineChartData = from dzien in Ostatnie7Dni
                                      join wplywy in WplywyPodsumowanie on dzien equals wplywy.dzien into dzienWplywJoined
                                      from wplywy in dzienWplywJoined.DefaultIfEmpty()
                                      join wydatki in WydatkiPodsumowanie on dzien equals wydatki.dzien into wydatkiJoined
                                      from wydatki in wydatkiJoined.DefaultIfEmpty()
                                      select new
                                      {
                                          dzien = dzien,
                                          wplywy = wplywy == null ? 0 : wplywy.wplywy,
                                          wydatki = wydatki == null ? 0 : wydatki.wydatki,
                                      };

            //najnowsze transakcje
            ViewBag.NajnowszeTransakcje = await _context.Transakcjes
                .Include(i => i.Kategoria)
                .OrderByDescending(j => j.Data)
                .Take(5)
                .ToListAsync();
            
            
            
            return View();
        }

    }

    public class SplineChartData
    {
        public string dzien;
        public int wplywy;
        public int wydatki;

    }

}

Manager Wydatków/Views/StronaG/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["isStronaG"] = true;
}

@*Podsumowanie*@
<div class="row mb-4">
    @*Wplywy*@
    <div class="col-md-4">
    <div class="d-flex flex-row widget summary income">
        <div class="d-flex flex-column justify-content-center p-5">
            <i class="fa-solid fa-dollar-sign fa-2xl"></i>
        </div>
        <div class="d-flex flex-column m-auto py-3">
            <span class="lead">Suma Wpływów</span>
            <h1 class="display-6 fw-bold">@ViewBag.sumaW</h1>
        </div> 
    </div></div>
    @*Wydatki*@
    <div class="col-md-4">
        <div class="d-flex flex-row widget summary expense">
        <div class="d-flex flex-column justify-content-center p-5">
            <i class="fa-solid fa-dollar-sign fa-2xl"></i>
        </div>
        <div class="d-flex flex-column m-auto py-3">
            <span class="lead">Suma Wydatków</span>
            <h1 class="display-6 fw-bold">@ViewBag.sumaWw</h1>
        </div>
        </div>
    </div>
    @*Stan konta*@
    <div class="col-md-4">
    <div class="d-flex flex-row widget summary balance">
        <div class="d-flex flex-column justify-content-center p-5">
            <i class="fa-solid fa-dollar-sign fa-2xl"></i>
        </div>
        <div class="d-flex flex-column m-auto py-3">
            <span class="lead">Stan konta</span>
            <h1 class="display-6 fw-bold">@ViewBag.stanK</h1>
        </div>
    </div>
    </div>
</div>

@*Wykresy*@
<div class="row mb-4">
    <div class="col-md-4">
        <div class="widget chart">
            <div class="p-4">
                <h5 class="fw-bold">Kategorie Wydatków</h5>
            </div>
            <ejs-accumulationchart id="wykres" background="#1a222b">
                <e-accumulation-series-collection>
                    <e-accumulation-series dataSource="@ViewBag.DoughnutChartData"
                                           xName="kategoriaTytulIkona" yName="cena" innerRadius="60%" legendShape="Circle"
                                           palettes=@(new string[]{"#0e8d76","#a4b219","#cb9b00","#8a442c","#0454b5","#7d0a0a","#822690","#4c2090","#313e93","#0096ac"})>
                    <e-accumulationseries-datalabel name="cenaFormat" visible></e-accumulationseries-datalabel>
                </e-accumulation-series>
                </e-accumulation-series-collection>
                <e-accumulationchart-legendsettings position="Top" toggleVisibility="false">
                    <e-legendsettings-textstyle color="#fff" size="1rem"></e-legendsettings-textstyle>
                </e-accumulationchart-legendsettings>
                <e-accumulationchart-tooltipsettings enable></e-accumulationchart-tooltipsettings>
            </ejs-accumulationchart>
        </div>
    </div>
    <div class="col-md-8">
        <div class="widget chart">
            <div class="p-4">
                <h5 class="fw-bold">Wpływy i Wydatki</h5>
            </div>
            <ejs-chart id="spline-chart" background="#1a222b"
                       palettes=@(new string[]{"#54ffa9","#f44336"})>
                <e-chart-primaryxaxis valueType=Category>
                    <e-majorgridlines width="0"></e-majorgridlines>
                </e-chart-primaryxaxis>
                <e-chart-primaryyaxis>
                    <e-majorgridlines width="1" color="#32414d" dashArray="3,5"></e-majorgridlines>
                </e-chart-primaryyaxis>
                <e-chart-chartarea>
                    <e-chartarea-border width="0" ></e-chartarea-border>
                </e-chart-chartarea>
                <e-series-collection>
                    <e-series dataSource = "@ViewBag.SplineChartData" xName="dzien" width="3"
                    yName="wplywy" name="Wplywy" type="@Syncfusion.EJ2.Charts.ChartSeriesType.Spline"></e-series>
                    <e-series dataSource="@ViewBag.SplineChartData" xName="dzien" width="3"
                    yName="wydatki" name="Wydatki" type="@Syncfusion.EJ2.Charts.ChartSeriesType.Spline"></e-series>
                </e-series-collection>
                    <e-chart-legendsettings position="Top" alignment=Far toggleVisibility="false">
                    <e-legendsettings-textstyle color="#fff" size="1rem"></e-legendsettings-textstyle>
                    </e-chart-legendsettings>
                    <e-chart-tooltipsettings enable shared></e-chart-tooltipsettings>
            </ejs-chart>
        </div>
    </div>
</div>

@*Najnowsze transakcje*@
<div class="row">
    <div class="col-md-6">
        <div class="widget">
            <div class="p-4">
                <h5 class="fw-bold">Najnowsze transakcje</h5>
            </div>
            <div class="px-4 pb-4">
                <ejs-grid id="recent-transactions" dataSource="@ViewBag.NajnowszeTransakcje">
                    <e-grid-columns>
                        <e-grid-column headerText="Kategoria" field="KategoriaTytulIkona"></e-grid-column>
                        <e-grid-column headerText="Data" field="Data" type="date" format="dd-MMM-yy"></e-grid-column>
                        <e-grid-column headerText="Cena" field="CenaFormat" textAlign=Right></e-grid-column>
                    </e-grid-columns>

                </ejs-grid>
            </div>
        </div>
    </div>
</div>

Manager Wydatków/Views/StronaG/Login.cshtml
@model Manager_Wydatkow.Models.User
@{
    Layout = null;
}

<head>
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <div class="center">
        <h1>Logowanie</h1>       

        @using (Html.BeginForm("Login", "StronaG", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
            <div class="txt_field">
             @Html.TextBoxFor(m => m.Username, new { @class = "form-control", id = "Username", placeholder = "Username", required = "required", autofocus = "autofocus" })
            <span></span>
            </div>
            <div class="txt_field">
            @Html.TextBoxFor(m => m.Password, new { @class = "form-control", type = "Password", placeholder = "Password", required = "" })
            <span></span>
            </div>        
            <div class="alert-danger">
            @if (ViewData["LoginFlag"] != null)
            {
                @ViewData["LoginFlag"]
            }
            </div>
            <button class="login" type="submit">Zaloguj się</button>
    }
    </div>

</body>